### ISSUE TITLE
0.6.3 expiry breaks JWT exp token format

### ISSUE THREAD

**Issue by owentran** [sahat/satellizer#121]
See issue #108, but the code is checking Javascript Date.Now() which returns milliseconds since epoch (UTC) vs. the server which is implemented as seconds since epoch on most UNIX systems.

Can you adjust the method to convert the millis to seconds with a Date.Now/1000?

**Comment by yahyaKacem** [comment]
Hi, I know this closed and really old but what about when the `exp` is in milliseconds I have that use case and the isAuthenticated method return true even if the token is expired because is compares the current time in seconds with the token `exp` in milliseconds couldn't this be configured by the developer?
couldn't be another option to the $authProvider for time unit?
