### ISSUE TITLE
Satellizer and subdomains

### ISSUE THREAD

**Issue by JonathanZWhite** [sahat/satellizer#190]
Hi there,

Satellizer has been working great for me so far! However, I recently changed the way that my urls work so that each user has their own submain i.e. user1.domain.com. However, I noticed that it seems like Satellizer maintain the same authorization status across subdomains? Is there any way to remedy this? Thanks.

**Comment by cliffordoravec** [comment]
Another workaround is to use cookies as storage, since you can use cookies across subdomains.

This would behave like the CSRF prevention cookie-to-header token approach - the cookie just stores the token and it is ignored by the server, since the server only looks for that value in a certain header value (**Bearer**).  Here, Satellizer would do a `get` against its storage service to retrieve the value out of storage (in a cookie) and pass that value as the **Bearer** header value (normal behavior).

Although Satellizer doesn't support this out of the box, you can throw a decorator at it and get the intended results (like so):

```
angular.module('satellizer')
.requires.push('ngCookies');

angular.module('satellizer')
.decorator('SatellizerStorage', function($delegate, $cookies) {
  var storage = {
    get: function(key) {
      return $cookies.get(key);
    },
    set: function(key, value) {
      $cookies.put(key, value, { path: '/', domain: '.domain' });
    },
    remove: function(key) {
      $cookies.remove(key);
    }
  };

  return storage;
});
```

This requires ngCookies.  You would put this after you include Satellizer but before your app actually runs.
