### ISSUE TITLE
Satellizer + Cordova functionality

### ISSUE THREAD

**Issue by mrantivirus** [sahat/satellizer#212]
I'm trying to get my cordova app working with Satellizer, but if I leave the code as is, then Facebook gives the error "redirect_uri" must be absolute. So, I modified the satellizer code to change the currentUrl string. Since I'm testing on android, the currentUrl is file:///, so I tried changing it to http://localhost, which then allows me to login via the Facebook website, not app. Once I do that, then I get an application error "net:ERR_CONNECTION_REFUSED(http://localhost/?code=AND_SO_ON)". I am lost at where to go from here since I'm new to mobile development.

Are there any suggestions you can provide?

I guess I should also mention that I'm running my web app/mobile app locally, so I don't have a domain setup or anything, that is why I did localhost.

**Comment by nagappan** [comment]
@Mr-Antivirus were you able to work with Satellizer and Cordova ? Do we need to make any special settings ? Satellizer just worked fine with browser, so I integrated with Cordova and when I tried login, noticed the following message in stdout.log:

2015-01-11 03:26:13.180 TestApp[76120:7508846] Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)
2015-01-11 03:26:16.360 TestApp[76120:7508846] Resetting plugins due to page load.

Any help is highly appreciated.

**Comment by Mr-Antivirus** [comment]
For me, it worked out of the box with the slight modifications Sahat provided above. Those errors you are seeing, look to be something completely unrelated though. Try removing satellizer or create a separate app with only satellizer and see if the issue persists.

**Comment by rrNuvoPoint** [comment]
Some of you had same issue as https://github.com/sahat/satellizer/issues/497?

**Comment by gakshat14** [comment]
I'm having same problem, just one question I wanted to ask- what do you mean by 'IP_OF_SERVER' in this context?? does it mean the server that is running the backend??

**Comment by alereisan** [comment]
same problem:

> Application Error
`net::ERR_CONNECTION_REFUSED /http://localhost/?code=4/....`

after clicking authenticating with facebook or google - can't redirect to the app.

**Comment by gakshat14** [comment]
Try to update your cordova inApp browser plugin.
