### ISSUE TITLE
Missing Authorization code

### ISSUE THREAD

**Issue by rahil471** [sahat/satellizer#225]
Hi I'm receiving this message after the popup closes in back-end implementation with node.js

`{"message":"Missing authorization code"}`

**Comment by sahat** [comment]
It's really hard to give any feedback without more information. Post a screenshot. Describe which library are you using, if any. Are you referring to my Node.js back-end implementation or your Node.js app?
The only message that is remotely similar in my Node.js demo is:
```js
if (!req.headers.authorization) {
    return res.status(401).send({ message: 'Please make sure your request has an Authorization header' });
  }
```
That occurs if your Angular app does not send a request with a header `Authorization: Bearer JSON_WEB_TOKEN`. And that would happen if there is something wrong with the HTTP interceptor in Satellizer which is responsible for adding that Authoriztion header.

Since this issue is over a month old I am going to close, however, if you are still trying to resolve it, re-open this issue and post more information next time so I can help you out.
