### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by bslipek** [sahat/satellizer#24]
Do Satelizer support IE ?
Because i have problem when try to authorize on IE (11,10 or 9), after log-in in provider window the pop-up close and nothing else happend, user is still not log-in.

**Comment by jgentes** [comment]
FYI - as it turns out, I had two different versions of satellizer.

One version was configured in `package.json` for Node, and the other was in `bower.json` for Angular. Satellizer in Angular was old, so once I updated it the problem went away. It was confusing because I thought I was up to date when I was looking at my package.json file.

**Comment by arterzatij** [comment]
may be this is a related issue, some of yours comments looks like my issue. Using localhost on IE.

https://github.com/sahat/satellizer/issues/349

**Comment by prashantmishraimpinge** [comment]
Hi Sahat,

I am following this conversation and used code that pushed to Github https://github.com/sahat/satellizer/releases/tag/0.7.0

I am having issues with FB app's in-app browser. It doesn't let my facebook login working properly.

Any guess?

Thanks in advance.

**Comment by Raviteja157527** [comment]
Hi Sahat,

I am having problem in IE 11. Popup doesn't close after login.

Facebook, twitter and linkedin have same problem in IE. It works fine in safari, FF and Chrome 

Please let me knaw if i am doing any wrong in implementing the code.

this the file i am using apart from satellizer.js

[socialMediaConfig.zip](https://github.com/sahat/satellizer/files/193512/socialMediaConfig.zip)


Thanks
Raviteja
