### ISSUE TITLE
adding support to the current user

### ISSUE THREAD

**Issue by artmees** [sahat/satellizer#266]
I think it would be great addendum if satellizer could support `currentUser` method...

this method (IMHO) should handle persisting the current user (JSON object) to the localStorage and retrieval of it... the same way it handles the auth_token ?

that way users who are using this "gem" could depend on it for handling `currentUser` without the need of separate service implemented just for that...

what do you think ?

**Comment by sahat** [comment]
Hey @artmees, I will not be adding it because `currentUser` functionality can be implemented in so many different ways. It could be stored in the JWT or it could be fetched from the server via an XHR. Plus, I don't want to keep it adding and adding more features to Satellizer. It has its use and purpose in its existing state. I would much rather focus on improving test coverage, closing existing issues, refactoring code than adding new features at this point.

**Comment by artmees** [comment]
:+1:
