### ISSUE TITLE
User Profile Picture

### ISSUE THREAD

**Issue by denzelwamburu** [sahat/satellizer#280]
Hey,
Great stuff there,
While logging in with other social accounts,it can't seem to pull the user image.
I have used a project that you made https://github.com/sahat/hackathon-starter and it puts the user image in the header and is working perfectly,can you replicate the same for this project?

**Comment by sahat** [comment]
In **controllers/contact.js** is where you pass your SMPT provider username and password:

```js
var transporter = nodemailer.createTransport({
  service: 'SendGrid',
  auth: {
    user: secrets.sendgrid.user,
    pass: secrets.sendgrid.password
  }
});
```

It probably refers to that login error. The default username and password I provided in this project were probably banned since this is a sensitive information that you shouldn't share with anyone. I, however did it for convenience reasons.

**Comment by sahat** [comment]
Ok, I have added profile picture support for Google so far. Will send a PR as soon as I am done with other providers, and if you would like to contirbute you could replicate that same functionality for other languages - Python, Java, PHP, etc.

![screenshot 2015-02-10 15 22 17](https://cloud.githubusercontent.com/assets/544954/6138756/bdf398fe-b138-11e4-95b9-63aec1934759.png)

**Comment by sahat** [comment]
I have updated GitHub, LinkedIn, Facebook, Google and Foursquare authentication routes to retrieve profile image. Did not update Twitter because it would requre an additional request and that route is already complicated as it is.
