### ISSUE TITLE
No localStorage check causes error

### ISSUE THREAD

**Issue by sabrehagen** [sahat/satellizer#293]
My server collects all of the client side errors in our app. It recently got the following stack trace:

 client error: {
    "errorUrl": "https://stemn.com/users/",
    "errorMessage": "TypeError: localStorage is null",
    "stackTrace": [
        "([object Object])@https://stemn.com/assets/js/satellizer.min.js:6",
        "([object Object])@https://stemn.com/js/angular/angular.js:2770",
    ]
............

According to this post it seems that this can occur if localStorage is disabled on the client. Maybe there should be a check put in to ensure localStorage 'exists'/is available before accessing it? http://stackoverflow.com/questions/12267903/firefox-typeerror-localstorage-is-null

**Comment by sahat** [comment]
Local Storage is the only type of store that Satellizer uses. If someone chose to disable the local storage in their browser, whether `TypeError` is thrown or a nice error message is displayed, Satellizer would not work either way.

**Comment by sabrehagen** [comment]
Certainly, but the most beneficial solution would be one that alerts why satellizer is failing, and a potential way to remedy the issue.

**Comment by lukaszbros** [comment]
I encountered the same issue with my application. I use external tool wkhtmltopdf as a printing mechanism for some of the pages. Unfortunately it does not support local storage. Due to lack of check for localStorage on the Satellizer side whole application is not able to initialise and I got blank page as result. The part that is failing is 

```
.config(['$httpProvider', 'satellizer.config', function($httpProvider, config) {
      $httpProvider.interceptors.push(['$q', function($q) {
        var tokenName = config.tokenPrefix ? config.tokenPrefix + '_' + config.tokenName : config.tokenName;
        return {
          request: function(httpConfig) {
            var token = localStorage.getItem(tokenName);
            if (token && config.httpInterceptor) {
              token = config.authHeader === 'Authorization' ? 'Bearer ' + token : token;
              httpConfig.headers[config.authHeader] = token;
            }
            return httpConfig;
          },
          responseError: function(response) {
            return $q.reject(response);
          }
        };
      }]);
    }]);
```
I do not require Satellizer running for printing purposes but as this is a config section I cannot avoid this code to be executed. I do not even use interceptor in my application and have config.httpInterceptor set to false but token query is done before check.

It would be great if check for config.httpInterceptor would be done earlier or localStorage check would be added.

**Comment by sahat** [comment]
#325

**Comment by sabrehagen** [comment]
I think that given this issue is 28 days old, and the other one is 4 days old, that it should be the duplicate. Just a technicality :P More discussion is over there though...
