### ISSUE TITLE
Apache + Laravel not sending authorization headers

### ISSUE THREAD

**Issue by daliborkrejic** [sahat/satellizer#300]
Authorization header is used for apache basic auth and it's discarded if it's not in valid format.

A workaround is to add this rewrite rule into public/.htaccess:
```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

**Comment by sahat** [comment]
Hi @daliborkrejic there was another issue just like this one in the past. I did add `.htaccess` file with these rewrite rules, but I accidentally added it to the root of laravel example folder instead of `public` folder.

There is only one minor difference between previous issue #178 and your code:

```php
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

Is `%1` and `%{HTTP:Authorization}` in this case?

**Comment by sahat** [comment]
Ok I have this issue in 4f9fe3bb58c7883092c00ed650799c3b1bef7c52.
