### ISSUE TITLE
What's the difference between url and redirectUri?

### ISSUE THREAD

**Issue by hanfeisun** [sahat/satellizer#301]
My front-end and back-end is separated and deployed on different domains... 

I was wondering whether I should write front-end Url or back-end Url in `url` and `redirectUri` attributes.. And what is the difference between url and redirectUri?

    # I write back-end Url in url and front-end Url in redirectUri currently, but it didn't work.
    $authProvider.facebook
        clientId: '123'
        url: 'http://my-backend-app.com/authenticate/facebook'
        authorizationEndpoint: 'https://www.facebook.com/dialog/oauth'
        redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host + '/'
        scope: 'email'
        scopeDelimiter: ','
        requiredUrlParams: ['display', 'scope']
        display: 'popup'
        type: '2.0'
        popupOptions: { width: 481, height: 269 }

**Comment by sahat** [comment]
The `url` is referring to the back-end endpoint where you are handling the authentication.

The `redirectUri` is referring to this Site URL where provider (in this case Facebook) takes you back after successful authentication.

![screenshot 2015-02-28 11 10 51](https://cloud.githubusercontent.com/assets/544954/6427619/8b38bf74-bf3a-11e4-9e38-cf029e2273c0.png)

I used  `redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host + '/'` so that you don't have to hard-code the URL `http://localhost:3000` or `https://mysite.com`.

So inside the popup Facebook will redirect you back to http://localhost:3000?code=UNIQUE_AUTH_CODE_FROM_FACEBOOK where Satellizer will take over, strip out and parse that `code` param, and send it back to your back-end specified by the `url` property.

Hope that answers your question.

**Comment by hanfeisun** [comment]
Thanks, now I understand! :-)
