### ISSUE TITLE
Authentication fails when front-end and back-end codes are served from different domains

### ISSUE THREAD

**Issue by glsee** [sahat/satellizer#303]
In the front-end package, the domain of the authentication popup window is being checked against the domain of the main window in the function that polls for the result of the authentication:

```
popupWindow.document.domain === document.domain
```

This has made the Satellizer fails to work when front-end codes are served from a different domain from the back-end codes. I'm not sure if this is a bug or intentional. If it is intentional but what is the rationale for it?

**Comment by sahat** [comment]
At the moment when you initiate authentication you are taken to http://facebook.com or http://google.com and etc. At that point `popupWindow.document.domain` (provider's login page)  is not equal to `document.domain` (your website).

Satellizer will keep polling until that condition is true. That condition is true when you are successfully authorized with a third-party OAuth provider and it redirected you back to the Redirect URL you specified when you created an app with them.

That line can't be the cause of your issue. Many people, myself included, have successully used Satellizer where front-end and back-end are on separate domains.

**Comment by EvgeniyOnopko** [comment]
I have the same issue.
It occurs when i try to authorize using google account.
For example my url address is one.localhost.com, and redirect_uri which i pass to google is localhost.com/somePath.

I successfully authorize with my google credentials but popup window remains opened after redirect. Because this condition is false:
> popupWindow.document.domain === document.domain

**Comment by airatshigapov** [comment]
@EvgeniyOnopko could you please provide example of your oauth config? I'm facing the same issue and can't get rid of it.

**Comment by nzamani** [comment]
I think we have a similar issue using a simple web app and an ionic app. However, I think this is not an issue of satellizer, let me try to elaborate:

**Configuration:**
1. We deploy the web application to both [https://localhost:8181/satellizerdemo](https://localhost:8181/satellizerdemo) (for local dev) and https://www.mydomain.com/satellizerdemo (for production). These are the urls that users enter into the browser
2. On Facebook/Google/Twitter/... we have configured the redirect_uri as https://www.mydomain.com/satellizerdemo. In Javascript/satellizer we make sure to use that same redirect_uri for Facebook/Google/Twitter/...

Based on the configuration above we have the following uses cases:

* Case 1: User opens https://www.mydomain.com/satellizerdemo (production) and clicks the Facebook/Google/Twitter button
Everything works just as expected - OAuth works just fine:
 - Popup opens
 - user enters credentials
 - Facebook/Google/Twitter redirect to the redirect_uri https://www.mydomain.com/satellizerdemo
 - Popup closes 
 - Login successful... cool!

* Case 2: User opens [https://localhost:8181/satellizerdemo](https://localhost:8181/satellizerdemo) and clicks the Facebook/Google/Twitter button
This does not work as expected:
 - Popup opens
 - user enters credentials
 - Facebook/Google/Twitter redirect to the redirect_uri https://www.mydomain.com/satellizerdemo
 - Popup stays open forever until user closes it manually
 - Login failed... oops!

* Case 3: Ionic app fails as well

The case 1 works just fine.
However, the two other cases do not work at all. I have debugged case 2 a little. The problem (at least for case 2) is CORS. As per default or for "security reasons" it is not possible to access the popup's location.* data, i.e. location.host
In satellizer,js we see this here:

```javascript
var popupWindowOrigin = popup.popupWindow.location.host;
```

In case 2 we call the app via *[https://localhost:8181/satellizerdemo](https://localhost:8181/satellizerdemo)* and open a popup window that redirects to *https://www.mydomain.com/satellizerdemo*. Script from *[https://localhost:8181/satellizerdemo](https://localhost:8181/satellizerdemo)* cannot access for example popupWindow.location.host of a popup window that shows *https://www.mydomain.com/satellizerdemo* because of CORS. Try to set a breakpoint at the satellizer.js code from above and hit *popup.popupWindow.location.host* in your chrome console.

I did not try it out yet, but I think it should be possible to fix this issue by setting the correct CORS headers for the redirect_uri https://www.mydomain.com/satellizerdemo to something that allows [https://localhost:8181](https://localhost:8181) and whatever else... I guess that should work. However, this is some server configuration (but it is not difficult). Of course, we don't want this for https://www.mydomain.com/satellizerdemo, so maybe it would be a good idea to change the redirect_uri to something like https://www.mydomain.com/satellizerdemo/rest/oauth and set the CORS headers here... Maybe that could also solve case 3.

@sahat does that make sense to you?

**Comment by barryvdh** [comment]
I think I'm having the same problem. What do I have to configure when I have different domains or use Phonegap/Cordova, which doesn't really use a domain?

I get the Twitter popup, it asks for permission, is redirected okay and the token is shown, but it stops there. It doesn't close and the token isn't stored.
Upon close I get an error that it failed.

Could you point me in the right direction?

**Comment by barryvdh** [comment]
Ok, I think I understand better now:

The redirectUrl should point back to the local address (localhost, 127.0.0.1, etc) of the client side app. It doesn't actually process anything, it just reads the token from the query string.
Then an XHR request is sent to exchange the token for the actual JWT user token.

So make sure the `redirectUri` doesn't point to your server, but your client. And make the `url` point to your server.
I did have to manually set the redirect url (callback) to the referer, as it isn't passed to the server?

**Comment by bora89** [comment]
@barryvdh Thank you, your explanation helped me to understand the logic!
