### ISSUE TITLE
Facebook login on windows IE9 not working

### ISSUE THREAD

**Issue by alonle** [sahat/satellizer#305]
I have tried to login with Facebook to your example(https://satellizer.herokuapp.com) with IE9 on windows vista:
I'm getting the error:
"The redirect_uri URL must be absolute"
Can you please check?
Thanks

**Comment by sahat** [comment]
I don't have Windows Vista or IE9 unfortunately. I can guess and say the problem is here:
```js
redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host,
```

Although, I added that `||` (OR) part specifically to handle Internet Explorer that does not support `window.location.origin`.

The quick and easy way to fix the problem is by overriding `redirectUri` and hard-coding the URL yourself to http://localhost:3000` or `http://yoursite.com` when you set up a provider in `.config` block.

**Comment by alonle** [comment]
@sahat thanks, setting the redirectUri seem to work :-)

**Comment by sahat** [comment]
Great!
