### ISSUE TITLE
Logout api endpoint

### ISSUE THREAD

**Issue by TolotraRam** [sahat/satellizer#307]
Would it be possible to reach an api endpoint on logout since i really login on server side too ? the logout now just destroy the token and not logout the backend side.

**Comment by sahat** [comment]
You should create your own service or make an http request from within your controller where you call `$auth.logout`. Since logout returns a promise you can do the following:

```js
$auth.logout().then(function() {
  // send a request to your server to perform server-side logout
  $http.post('/logout').succcess(function() {
    console.log('Successfully logged out');    
  });;
});
```

I don't know how your logout is implemented, nor should Satellizer make any assumptions about it. With token-based authentication it is a little simpler. As you can see you my example does not have a server-side logout. You are always logged out. When you need to access protected route you have to send a valid token. But it seems you have a more complex scenario where you need to perform logout on the server as well.

**Comment by TolotraRam** [comment]
Hi, thanks for the fast response, and yes token-based auth is simpler but i use satellizer for a cordova project and want to implement a realtime application which need a server-side interraction. 
The solution work well. :)
