### ISSUE TITLE
Thoughts on separating out satellizer.js into separate files?

### ISSUE THREAD

**Issue by daviskoh** [sahat/satellizer#316]
IMO, this would make the project more modular and easier to maintain. 

The following changes would allow this to happen:
- break each Angular component (i.e. factory, provider, etc) into separate files that live in a /src directory
- add a build process that concats these together and wraps the combined file in an IIFE
- build process would output to a /dist directory where the final satellizer.js & satellizer.min.js files live

**Comment by sahat** [comment]
Everything you mentioned has already been done when Satellizer was around v0.7 or v0.8, but there were some issues with the loading order of these services when you break them apart instead of chaining:

![screenshot 2015-03-15 13 23 35](https://cloud.githubusercontent.com/assets/544954/6657932/a12b4eb8-cb16-11e4-93b8-f83678ae00a3.png)

In the end it was simpler to revert back, since many people were having login issues as a result of this change, than spending more time trying to get to the bottom of the problem.

Honestly, Satellizer is still fairly small and manageable even with a single-file approach.
