### ISSUE TITLE
Checking for "currentUser" doesn't work in the localStorage after page refresh

### ISSUE THREAD

**Issue by mukul-raina** [sahat/satellizer#321]
So I have been following the tutorials (http://sahatyalkabov.com/create-a-tv-show-tracker-using-angularjs-nodejs-and-mongodb/, https://hackhands.com/building-instagram-clone-angularjs-satellizer-nodejs-mongodb/#/login-page) and in the header I also check for 
`<li ng-if="isAuthenticated() && currentUser.email"><a href="">Hello {{ currentUser.email }}</a></li>`
`<li ng-if="currentUser"><a href="">Hello {{ currentUser.name }}</a></li>`

When I first start the app, both of these work when the user is logged in. However if I refresh the page, both of them stop working. I double checked and `currentUser` is still in the localStorage. Any idea what I could be doing wrong?

Thanks!

**Comment by sahat** [comment]
My first guess would be that the state is lost when you refresh the page. Your Angular controller no longer knows about the `currentUser` object. It is set during the initial login, but probably does not get re-set again on page refresh by pulling the value from local storage.

Which is why, in the TV Show Tracker example I always fetch the `currentUser` when factory is loaded, be it a page refresh or an initial load:

```js
$rootScope.currentUser = $cookieStore.get('user');
$cookieStore.remove('user');
```

So you will need to handle fetching `currentUser` from local storage yourself in your NavBar controller or one of the factories.

**Comment by mukul-raina** [comment]
Thanks @sahat, that made sense
