### ISSUE TITLE
AngularJS Satellizer CORS issue when authenticated

### ISSUE THREAD

**Issue by hosannahighertech** [sahat/satellizer#348]
I have almost same issue with the guy posted at SO http://stackoverflow.com/questions/28299297/angularjs-satellizer-jwt-cors-issue-when-authenticated

I find that after login with Satellizer, some headers are missing (in my case the CORS). How can I stop that without affecting login? I use only email/password login and Token bearer for subsequent queries.

**Comment by sahat** [comment]
@hosannahighertech I have successfully used Satellizer with CORS, so chances are you did not set up your server correctly to work with cross-origin requests.

What are you using for your back-end? Also, you can easily disable Satellizer's http interceptor and add your own if necessary.

**Comment by mtangoo** [comment]
Hi @sahat,
I forgot to logout from company's account (which I administer) so its me again. I have set up CORS corectly and I can see right response when am not logged in. When I log in is when some headers vanish. Do I need something special when am logged in with Satellizer?

**Comment by poxip** [comment]
`$authProvider.httpInterceptor = false;` worked for me.

**Comment by akkie** [comment]
I've the same problem with Twitter:
```
XMLHttpRequest cannot load https://twitter.com/oauth/authenticate?oauth_token=***********. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.
```

It seems that Twitter doesn't send the CORS header. Or do I miss something?

**Comment by sahat** [comment]
##### Scenario 1: Server running on `localhost:3000` and Client running on `localhost:8000` and CORS support is enabled via `cors` npm module and `$authProvider.withCredentials = true`
Twitter popup closes and an error is thrown.
<img width="1043" alt="screenshot 2015-08-15 02 28 11" src="https://cloud.githubusercontent.com/assets/544954/9288307/62d0ae9a-42f5-11e5-8654-c956e4b7f465.png">

##### Scenario 2: Server running on `localhost:3000` and Client running on `localhost:8000` and CORS support is enabled via `cors` npm module and `$authProvider.withCredentials = false`
<img width="1035" alt="screenshot 2015-08-15 02 31 36" src="https://cloud.githubusercontent.com/assets/544954/9288318/dffb45c4-42f5-11e5-9982-4a9f5b8bae75.png">

You can set `withCredentials` to false for now if you are running into a similar issue until I figure out what to do with it. I added it because someone requested it, but now it's causing more harm than good. Perhaps it should be set to false by default.

**Comment by roychowdhurysourav23** [comment]
I am having an issue while integrating google+ (oAuth2) login with angularjs 1.3.X .I made the changes as per the readme.md document but always having an error in saying.... 

Error: angular.merge is not a function
Oauth2.open@http://192.168.33.10/bower_components/satellizer/satellizer.js:434:13
Oauth.authenticate@http://192.168.33.10/bower_components/satellizer/satellizer.js:342:11
this.$get</$auth.authenticate@http://192.168.33.10/bower_components/satellizer/satellizer.js:204:20
$scope.google_login@http://192.168.33.10/scripts/controllers/headerController.js:34:13
$parseFunctionCall@http://192.168.33.10/bower_components/angular/angular.js:12456:15
@http://192.168.33.10/bower_components/angular-touch/angular-touch.js:481:9
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://192.168.33.10/bower_components/angular/angular.js:14555:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://192.168.33.10/bower_components/angular/angular.js:14654:18
@http://192.168.33.10/bower_components/angular-touch/angular-touch.js:480:7
jQuery.event.dispatch@http://192.168.33.10/bower_components/jquery/dist/jquery.js:4434:15
jQuery.event.add/elemData.handle@http://192.168.33.10/bower_components/jquery/dist/jquery.js:4121:6
	

return logFn.apply(console, args);


"angular.merge" is under satellizer.js library file. Please find me a solution.

**Comment by blackotruck** [comment]
@sahat using ```$authProvider.withCredentials = false``` is notworking for me, i'm not getting the wildcard error message but the  No 'Access-Control-Allow-Origin'. is there another workaround?

**Comment by abhishekbhardwaj** [comment]
BUMP. 

I think `$authProvider.withCredentials = false` should definitely be set to false by default.

**Comment by JessicaMulein** [comment]
I seem to have run into this issue as well. Lumen on the backend and some debugging is showing that I'm putting the CORS headers into the response, but the browser seems to be losing them.
