### ISSUE TITLE
[Suggestion] callback instead of POST to /auth/provider

### ISSUE THREAD

**Issue by elgs** [sahat/satellizer#378]
Instead of sending a POST request to /auth/provider, I think it's cleaner to make a callback in the client side, and leave it to the application to do whatever they like with the server, or even a server is not needed at all. Currently sending a POST request to /auth/provider assumes a server with certain url pattern to exists, which is not necessary, I think.

**Comment by sahat** [comment]
Hi @elgs, what you are suggesting would require a large rewrite of the library, and not necessarily for the better. Satellizer tries to make developer's life easier by using certain assumptions, such as back-end implementation for OAuth providers. If I take away that, then what's the selling point of having Satellizer? May as well just do everything yourself without using any libraries.

Server is needed unless you are doing an implicit grant type, which is not supported by all providers with OAuth 2.0. For Twitter and other OAuth 1.0 providers you definitely need a back-end. 

If you add `responseType: 'token'` to provider's configuration, it will skip POST request to /auth/provider. If you don't like the route naming, you can change it by updating `url` property in provider's configuration.

**Comment by elgs** [comment]
Thanks @sahat. What I initially was hoping is that Satellizer would do the token authorization, and the user profile retrieving all in the client side. Because what I need is just some basic user information like name and email. But as I explorer more in this wonderful library, I found it make sense to keep this process in the backend, as things like `client_secret` are sensitive information. If this is in the browser, it could be easily seen by everybody.

Now I'm implementing a Golang based backend. facebook, gihub and google are done. I would be happy to send my Golang code to you if you need it.

**Comment by sahat** [comment]
@elgs I have considered all options when developing Satellizer. I initially wanted to make it pure client-side authentication. You don't need to use client secret for that if you are doing an implicit grant type (client-side). However, that use case is only good if you are building a simple client app to interface with that API. But that's a bit unrealistic. You almost always want to grab that user information, send it to your server and save it to databse.

But how do you know the access_token and user information is sending to your server is actually correct? Malicious user could send any information they want. So, you then need to verify that access token or signature on the server anyway to make sure it is valid. Unfortunately, every provider is different. Google does it one way way, Facebook does it another way. LinkedIn requires you to be on HTTPS (which is a pain for local development). Some providers don't even support access token verification and implicit grant type.

However, everyone supports explicit grant type (server-side). Also, Twitter would not be possible to do using a pure client-side solution because it still uses OAuth 1.0.

**Comment by elgs** [comment]
Thanks @sahat. I appreciate your detailed explanation. Now I gained a lot of insights to this amazing library. It really make my life a lot easier, though at the first glance it was very complicated.
