### ISSUE TITLE
IONIC - never get user profile.

### ISSUE THREAD

**Issue by countrdd** [sahat/satellizer#379]
Using ionic and node...everything looks good, except on the server I see this after facebook auth

GET /?code=AQCzUU8Z6iQvsKxUDIHN8KPudobWc19wfz7rqTDyCry1ryRBL1NQQ6dVFao5ML5Q7YykYyge_S8LC_wkLqOW5BefTBlMXqRmZBclbZbxLdofqGBEVG9qujtNQCUT3ZByrh2nTZTKvvnA0d6lJ23uJUcQE7H7j4OxpYuxhD16oFV61IITo6BSkDfyB-P-Rn8hIlSvJvsYbDtpqiRcgOc_FMAyurwdFvzsKy2ksgC8xMUPHkE0hzSloy69nAKOhHY5TzdQVfWaH-XElmWgH_X2QgD47-aHxTWzcfzbFaE6pMQFZFdFL30q0Ae-Wgc_IjSmB2M 200 0.583 ms - 2343

what am I missing. It never returns a user object back to IONIC so I can get the user name etc.

**Comment by countrdd** [comment]
let me clarify. I see that call going to the server (node), but a user account is not created in mongo.

Any help would be greatly appreciated.

**Comment by sahat** [comment]
I still haven't got a chance to play with the Ionic Framework. @krystalcode do you have any advice for @countrdd ?

**Comment by countrdd** [comment]
It looks like it is GETTING the code to the server vs POSTING.

**Comment by countrdd** [comment]
Quicks Question - What is .platform = mobile for? 
and should there be a http.get for to exchange the code for a token?

**Comment by countrdd** [comment]
OK. - So First big issues. - bower.json in ionic example needs set to satelizer: ^0.10.1

One I fixed that the window (inapp browser would close correctly). 

With some console logging on...this is what is being returned from server.js (node) after the windows closes. I assume that FB is sending the auth code, but it is liske node.js server is not interpetting it right and is sending back this...

"data":null,
"status":0,
"config":{
"method":"POST",
"transformRequest":[
null
],
"transformResponse":[
null
],
"withCredentials":true,
"url":"/http://localhost.reeldealnetwork.com/auth/facebook/",
"data":{
"code":"AQBzsygLzCLCAjJMEaSbb83VUuvycPoK7L9V8kN7xp4h4Li71MGrXx1RPbECJ_ezGfcKZXAFjJWgqsgW2NrMXU0umtT1g0XVrYg3S6nRwNXJqn-METny_dzkfCcMwtPG7FnYOHx63Jaa2mZ7nYBcpjCD9AgJzQzxLPfhI9CWDRGA2E4IR_FgH4jIwF_L9Uay3B4lUj-fc4cuuRehG1c-ZqA_uroHOra6BympzyJ1G1CJNAtLlPthNef3XslXLnjYF8OjaeYSpI4EjfJsBoBCGu2yZNGCndpZQ8qrPHLicsQWt6DyOCakOg24niFHasPdIaNTv4e_DUrVV1MPHP59sEd6",
"clientId":"511642752211511",
"redirectUri":"http://localhost/"
},
"headers":{
"Accept":"application/json, text/plain, */*",
"Content-Type":"application/json;charset=utf-8"
}
},
"statusText":""
}

**Comment by countrdd** [comment]
Would LOVE to see the stack/yemoan generator (which is dead) utilizing satellizer instead of passport..

https://www.npmjs.com/package/generator-sean

From: Sahat Yalkabov
Reply-To: sahat/satellizer
Date: Wednesday, April 29, 2015 at 2:42 PM
To: sahat/satellizer
Cc: Dustian Countryman
Subject: Re: [satellizer] IONIC - never get user profile. (#379)


I still haven't got a chance to play with the Ionic Framework. @krystalcode<https://github.com/krystalcode> do you have any advice for @countrdd<https://github.com/countrdd> ?

**Comment by krystalcode** [comment]
Hi @countrdd ,

The full process should be that satellizer gets the code from the provider (Facebook), sends the code to the server. The server then needs to exchange the code with an access token so that it can make further requests to the provider's api, such as get the user details. It is up to you to implement this step server side. After exchanging the code with a token, you can make an extra request to the provider to get the user details, then create a user in your database (MongoDB), and sent back to Ionic the user details and your own application auth token so that the user is considered logged in for the purposes of your application.

Have you implemented these steps server side? My guess is that Satellizer works as expected but the server does not perform these steps. Satellizer does not provide these, you can have a look at the examples for nodejs in the examples folder though if you haven't already done so - or ask your server engineer if you are not developing the server side api. 

Responses to previous comments:

- The code is sent by the provider to the popup window as a GET request, and sent by Satellizer to the server as a POST request (see this line of code (satellizer.js 470): return $http.post(defaults.url, data, { withCredentials : config.withCredentials }); )

- The default value for $authProvider.platform is "browser". Retrieving the code from the popup window works differently in the browser than in the InApp browser. For this reason, when one of ionic.Platform.isIOS() and ionic.Platform.isAndroid() is true, the platform is set to "mobile" to instruct Satellizer that it should try to get the code the way it needs for mobile.

**Comment by krystalcode** [comment]
Also, f you are making a CORS request (which you most likely are if you're using Ionic), you'll need to have your server accept cross origin requests. If you have to do that using wildcards, you'll need to set the withCredentials value to false because the Access-Control-Allow-Origin header can't be a wildcard if credentials are used.

**Comment by satishimpingesolutions** [comment]
Hi,

I am getting two issues(Facebook in-app browser) that might be related to same problem.
- Pop-up is not getting closed 
- Facebook is unable to exchange token with my server.

"The default value for $authProvider.platform is "browser".

Do I need to change something to get it working? Here is the URL to my Satellizer.js file
[Satellizer JS Link](http://staging.juxtap.com/bower_components/satellizer/satellizer.js?v=35345436546)

Thanks,
