### ISSUE TITLE
Satellizer send OPTIONS and not POST

### ISSUE THREAD

**Issue by simkepal** [sahat/satellizer#430]
Hello,

I have a login problem whit facebook signin. I try to set the baseUrl to subdomain like api.mydomain.com. The problem is that my browser only sends the OPTIONS request, which is returned OK, status is 200, but than does not send the POST request. Other request for saving item, upload images and similar work OK, only satellizer is not sending POST. I have Laravel 5 for my api responses.

Can anyone help me, please. What could be wrong?

This is my config for satellizer...

$authProvider.baseUrl = 'http://api.mydomain.com';
$authProvider.facebook({
	clientId: '4343242342342',
	scope: 'public_profile',
	url: '/v1/social',
});

Thank you all!!

Best regards,
Simke

**Comment by Pietro-Vis** [comment]
Hi, usually the browser sends OPTIONS / preflighted requests to the server before the POST to check if the server accept the headers or the content type of your request. 
Please read this: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by satishimpingesolutions** [comment]
Hi,

I am getting two issues(Facebook in-app browser) that might be related to same problem.
- Pop-up is not getting closed 
- Facebook is unable to exchange token with my server.

"The default value for $authProvider.platform is "browser".

Do I need to change something to get it working? Here is the URL to my Satellizer.js file
[Satellizer JS Link](http://staging.juxtap.com/bower_components/satellizer/satellizer.js?v=35345436546)

any help? 

Thanks,

**Comment by mikehm** [comment]
I am having a similar issues with the local Login. Is there a common solution on the client side? Without specifying headers on the server?

**Comment by clarle** [comment]
Hi all,

This is due to how CORS works - it requires a pre-flight OPTIONS request to be sent in order for "approval" to be given by the server to perform a cross-domain HTTP request.  

You absolutely need to specify the CORS headers on the server for this to work.

You can find more information about the process here:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Overview

Let me know if you have any other questions, or feel free to re-open this issue if you think it may be a problem in the framework.

Thanks!
