### ISSUE TITLE
Safari Private Window localStorage error QUOTA_EXCEEDED_ERR: DOM Exception 22

### ISSUE THREAD

**Issue by redwood-egarcea** [sahat/satellizer#457]
When using satellizer in Safari Private Window, trying to use localStorage causes a QUOTA_EXCEEDED_ERR.  Apparently this is by design. Possible solution is to degrade from localStorage to using a cookie.

**Comment by sahat** [comment]
@redwood-egarcea I will merge your PR but could you please fix the merge conflict first?

I was initially against using this local storage module to avoid having any dependencies, but since then I had to create a `storage` factory and reimplement some functionalities that are already provided by `angular-local-storage`.

**Comment by redwood-egarcea** [comment]
Updated pull request with passing tests and minified code.

**Comment by sahat** [comment]
Thanks, I will take a look at it after work.

**Comment by sahat** [comment]
Fixed in in [0.12](https://github.com/sahat/satellizer/releases/tag/0.12.0) release.
