### ISSUE TITLE
Twitter redirectUri

### ISSUE THREAD

**Issue by barryvdh** [sahat/satellizer#460]
Is there a reason that the Twitter API doesn't use a `redirectUri`? Shouldn't that also default to the document origin?

**Comment by sahat** [comment]
Twitter's OAuth 1.0 is considerably different from OAuth 2.0. You don't go directly to the Authorization popup screen from your client-side app. Satellizer will initiate a POST request to the server, the server hits one of Twitter's endpoints to obtain request token. This request token is then sent back to the client-side app. Only at this point OAuth 1 and OAuth 2 flows are more or less similar.

I could pass redirect uri from the client-side but it doesn't really make much difference. In fact, since consumer key and consumer secret are already accessed from the server, might as well access redirect uri from the server as well.

```js
  var requestTokenOauth = {
      consumer_key: config.TWITTER_KEY,
      consumer_secret: config.TWITTER_SECRET,
      callback: config.TWITTER_CALLBACK
    };
```

Do you have a valid use case for sending it from the client-side?

**Comment by barryvdh** [comment]
I can set it in the server, but for multiple clients, it might be easier to send it to the server from the client, right?

**Comment by sahat** [comment]
What do you mean by multiple clients?

**Comment by barryvdh** [comment]
Like iPhone/android (cordova) apps and online version of angular app. They have different callback urls right? Now I just set the the redirect to the referrer. Or am I using it wrong?

**Comment by sahat** [comment]
Ah, right, I forgot that Ionic uses `http://localhost` for its redirectUri, so that presents a problem if you wish to use the same keys for web and ionic apps.

**Comment by sahat** [comment]
Take a look at `satellizer.js` when you get a chance. I have tested it with browser and ionic examples and  it seems to work fine.

Twitter example now uses `redirectUri` just as any other OAuth 2 provider.
```js          
redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host,
```

**Comment by barryvdh** [comment]
I've checked. The `redirectUri` is passed to the server on the first request, but not on the second request. It should probably send them to both, as the redirect param is needed on both requests (and need to be the same), right?

**Comment by barryvdh** [comment]
Sorry my bad! The callback isn't used the second time. It's working now :)

**Comment by sariyu** [comment]
Hi @sahat, when i try to use satellizer with ionic app i'm getting an error. same code working fine with angularjs web application. redirecturi , i used in ionic is 'http://localhost' but i came to know that window.location.origin for ionic app is 'file://' it should return the response back to location.origin to work properly. Any IDEA on it ? @barryvdh
