### ISSUE TITLE
Problems with id_token response_type

### ISSUE THREAD

**Issue by digitalinfamy** [sahat/satellizer#483]
Hi all.

I'm not sure if this is a satellizer issue or a Noob rtfm issue? but after really struggling with satellizer and using IdentityServer for asp.net I've come across this issue.

basically my popup box would not go away.  I set up an webapi controller to handle the post on redirect but the token returned would just hit the page and display as JSON.  I tried a number of redirect scenarios but nothing seemed to match up e.g. I got 405 if the redirect was to a standard html page, I got the token displaying in the popup if it was a webapi post response... 

Any way to cut a long story short after some digging I noticed that in the return openPopup.then method response type only checks for 'token' and not 'id_token' or 'id_token token'.  I've added checks for all 3 scenarios and now it's all working fairly well.

is this because I'm doing something stupid or are the additional checks valid? 

Thanks for a great lib though guys :)

**Comment by sahat** [comment]
Hey @digitalinfamy, no you are not doing anything stupid, I just haven't tested this library with Identity Server. With OAuth there are two response types - `code` (explicit grant) and `token` (implicit grant). That's why you only see those response types in Satellizer.

If I find an elegant way to customize OAuth responseType via `$authProvider`, I will add that support, so you can specify any response type per provider. But for now, you can assume it's not supported and just use your own workarounds.
