### ISSUE TITLE
Twitter auth error with NodeJS + Ionic

### ISSUE THREAD

**Issue by miguelcrespo** [sahat/satellizer#511]
Hi. 

I am experiencing an error with twitter login inside an ionic App, this used to work sometime before stopping working without any changes. This is the error:

![screenshot from 2015-08-05 18 58 57](https://cloud.githubusercontent.com/assets/5839623/9100849/2347391c-3ba5-11e5-9805-d34c0832791c.png)

**Flow:**

1. The user hits the button for twitter auth
2. On the server this error occurs:
**TypeError: Cannot read property 'oauth_token' of undefined in this line:**

On the lines: 

    if (!req.body.oauth_token || !req.body.oauth_verifier){
    /* code */
    }
3. The flow stop with the windows show above.

This happens because satellizer make the request via GET instead POST to the server without any parameters and I don't know how to solve this.

Thank you very much.

**Comment by miguelcrespo** [comment]
Any help?

**Comment by sahat** [comment]
Pro Tip: In JavaScript, whenever you encounter `TypeError: Cannot read property 'oauth_token' of undefined`, look at the object that uses `oauth_token` property. It's `body`, namely POST body which is undefined. I haven't used Sails.js, but I assume body-parser module for parsing POST requests is built-in, so the only reason why it would be undefined is probably because Satellizer is doing a GET request as you suggested.

As of Satellizer 0.11.x Twitter is now consistent with other OAuth providers, it now makes a POST request. So, my guess is you are using an older version of the library and a new version of the node.js server example.
