### ISSUE TITLE
Twitter example not working with newest guzzle

### ISSUE THREAD

**Issue by Sebi55** [sahat/satellizer#553]
I am trying to setup twitter login for my app but I always get a Client Error: 400 back. I have got the facebook login working but twitter doesn't work.
I tried to use the example given but since it uses an old guzzle version and I am using the latest one I cannot figure out how to achieve the same things with my guzzle version.

The examples fails here:
```php
$requestTokenOauth = new Oauth1([
              'consumer_key' => Config::get('app.twitter_key'),
              'consumer_secret' => Config::get('app.twitter_secret'),
              'callback' => Config::get('app.twitter_callback')
            ]);
            $client->getEmitter()->attach($requestTokenOauth);
            // Step 1. Obtain request token for the authorization popup.
            $requestTokenResponse = $client->post($requestTokenUrl, ['auth' => 'oauth']);
```
The new guzzle version does not support getEmitter.
I tried many different ways to include the $requestTokenOauth in my POST but I always get back Client Error: 400
My current version looks like this but this was not my best try.
```php
$requestTokenOauth = [
              'consumer_key' => Config::get('app.twitter_key'),
              'consumer_secret' => Config::get('app.twitter_secret'),
              'callback' => Config::get('app.twitter_callback')
            ];
            // Step 1. Obtain request token for the authorization popup.
            try {
              $requestTokenResponse = $client->post($requestTokenUrl, ['auth' => 'oauth', 'query' => $requestTokenOauth]);
            } catch (RequestException $e) {
              return $e->getResponse()->getBody()->getContent();
            } catch (\Exception $e) {
              return $e;
            }
```
Nevertheless I cannot figure out why this does not work. Maybe someone of you have already upgraded to the newest guzzle and can tell me how to get it working.

**Comment by JustinLien** [comment]
@Sebi55 I ran into this issue and decided to fall back on 5.3 since there's a bit of changes check their [releases](https://github.com/guzzle/guzzle/releases). You'll need to make sure you have the latest guzzle/oauth-subscriber as well since the older version does not work < 6.0. 

If you really need to use the latest version check [guzzle/oauth-subscriber](https://github.com/guzzle/oauth-subscriber) they have the full working example for Twitter.

**Comment by Sebi55** [comment]
@JustinLien I just had a look at everything and also downgraded since I just could not get it working. It took me 8 hours to revert all changes since I was using JWTAuth and not only JWT. I am pretty happy with the current solution since Twitter works now and everything else too.

**Comment by sahat** [comment]
@JustinLien @Sebi55 Laravel example has been upgraded to v5.2 and now uses Guzzle 6 and the latest version of oauth-subscriber. Here is the commit for Twitter Auth controller changes: https://github.com/sahat/satellizer/commit/3231f7635766b921c64ac496d07b7719875fe28a

**Note:** I had to append `token` and `token_secret` to OAuth requests because the library complains if you do not include it (you shouldn't have to in this case). There is already an open issue and pull request regarding this issue for guzzle/oauth-subscriber.
