### ISSUE TITLE
password/username forgot function

### ISSUE THREAD

**Issue by do-n-khanh** [sahat/satellizer#554]
Could you please add function that allow user to retrieve their password/username in case they forget it?

**Comment by sahat** [comment]
How do you imagine that function would work? The entire "Forgot password" flow is handled on the server. So, there is very little benefit I see in adding it, when you could make your own service and your own HTTP requests for that. 

Some people who are not familiar with the password reset flow at all, may mistakenly think that Satellizer magically reset user's password for them because it has a function called `$auth.passwordReset()`.

I suggest to take a look at one my tutorials on how to [implement password reset](http://sahatyalkabov.com/how-to-implement-password-reset-in-nodejs/) in Node.js and adapt it your back-end.
