### ISSUE TITLE
Any way to have satellizer NOT put the Authorization token to ajax call not going to my own server?

### ISSUE THREAD

**Issue by swrocket** [sahat/satellizer#577]
Right now, even when I make a call to an external API, it sends the authorization toke, which it shouldn't.

Thanks,

Andrew

**Comment by sahat** [comment]
Right now it's either opt-in or opt-out approach, but you can disable it and then send Authorization token yourself for just the endpoints you want.

```js
$authProvider.httpInterceptor = false;
```

Then manually add `Authorization: Bearer <token>` to your $http request headers.

**Comment by Hypocrite** [comment]
I think this would be a good enhancement.

I am trying to integrate Google maps to our application and make GET requests to Google Maps API.

But the problem is that the application sends the authentication header with all $http requests which Google Maps API does not allow.

Would be good if you could only send authentication headers to your application and not external requests.

If you have a good alternative solution for this, I would be happy to hear it.

**Comment by craigivemy** [comment]
+1

**Comment by guillaumegarcia13** [comment]
+1

**Comment by pablo-dave** [comment]
+1
