### ISSUE TITLE
Add InAppBrowser Setting for target: _system

### ISSUE THREAD

**Issue by gamejerksnet** [sahat/satellizer#586]
Currently within the code you have hard coded `_blank` if it is a `config.cordova: true` but that just uses the InAppBrowser only, I found it hard to logout of Facebook via the InAppBrowser so that someone else could login with their social provider without me having to set both `clearcache` and `clearsessioncache` to "yes" every time requiring the login.

If given the option to use `_system` vs `_blank` on cordova apps it will tell the InAppBrowser plugin to use the device's default browser which in theory would already be logged into the provider, and make it easier to logout of the provider in order to sign into a different account via authenticate.

```js
    var stringifiedOptions = Popup.stringifyOptions(Popup.prepareOptions(options));
    var windowName = config.cordova ? '_blank' : name;
```

I'm not sure how you would wanna allow that to be configured through the `$authProvider` in `config()`.

**Comment by sahat** [comment]
@gamejerksnet I would prefer to use `_system` as well. Frankly, I didn't know it existed. Ionic example was contributed by someone else, so I haven't done much documentation digging. 

The only issue is what happens after user authorizes successfully?

As you may know, the way it works right now - it will redirect back to the starting point (localhost or localhost:3000 in this case), it will check if `code` or `token` parameter is present in URL, if it is, grab it and close the popup window.

What happens when I change _blank to _system is that Safari (system browser) will redirect to `localhost`(invalid URL) instead of closing the popup and navigating back to the app. That navigation back to the app is something I am not familiar with and not even sure if Cordova has an API for this? More info on this is appreciated.

**Comment by sahat** [comment]
After doing some research, it doesn't look like it is possible to use system browser for OAuth. That's one limitation of the InAppBrowser at the moment.You can start the OAuth flow via Mobile Safari, but it will have no way of transferring control back to the Ionic app.

**Comment by amrynsky** [comment]
Just wondering, would it be possible to use Custom URL Scheme to return back to the app?

**Comment by sahat** [comment]
@amrynsky I don't know. My iOS experience is extremely limited. If someone successfully manages to get it to work via Custom URL scheme, I will re-open this issue to discuss further steps.
