### ISSUE TITLE
render_success and render_error missing

### ISSUE THREAD

**Issue by ACPK** [sahat/satellizer#602]
For the RoR example app, I don't see the render_success and render_error methods in the application controller.  Are they somewhere else (i.e. a gem)?

**Comment by sahat** [comment]
To be honest, I haven't even looked at it much. It was contributed by @simonasdev.
@elanperach did a PR submission as well, so he may know more.

**Comment by simonasdev** [comment]
Oh shit :D I'll look into it. Probably going to submit PR today

**Comment by simonasdev** [comment]
Yeah, the only problem is that @Adam-Goldman7 wrote those two controller actions, so we can't really know what he meant with them. From the structure it seems that simple fixes could look like this:
```ruby
class AuthController < ApplicationController
  # Ommitted
  private
    
  def render_success data
    render json: data, status: 201 # or 200
  end

  def render_error message
    render json: { error: message }, status: 401 # or 422
  end
end
```

**Comment by Adam-Goldman7** [comment]
Only now seeing this, sorry for the late response @ACPK !

I've made the RoR server example with @elanperach maybe ...
6 month ago?

I haven't used it nor coded in RoR since.

These two methods are here:


        def render_data(data, status)
          render json: data, status: status, callback: params[:callback]
        end

        def render_error(message, status = :unprocessable_entity)
          render_data({ error: message }, status)
        end

        def render_success(data, status = :ok)
          if data.is_a? String
            render_data({ message: data }, status)
          else
            render_data(data, status)
          end
        end

Is there anything else missing?

I'm not involved in the project where we've implemented it anymore, let me know if there's something else missing and I'll add what's needed or direct it to @elanperach

**Comment by sahat** [comment]
Thanks everyone. I will update the example code. @ACPK if that solves your issue, you may close this issue.
