### ISSUE TITLE
Error on Access-control-Allow credentials header is not true

### ISSUE THREAD

**Issue by pavankumarkatakam** [sahat/satellizer#603]
Successfully created project in the google console and app also, but im getting this error

XMLHttpRequest cannot load http://www.example.com/basic/socialcontacts/google. Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials.

**Comment by clarle** [comment]
Hi @pavankumarkatakam,

This is due to how CORS works - it requires a pre-flight OPTIONS request to be sent in order for "approval" to be given by the server to perform a cross-domain HTTP request.

You can find more information about the process here:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Overview

Let me know if you have any other questions, or feel free to re-open this issue if you think it may be a problem in the framework.

Thanks!
