### ISSUE TITLE
Facebook graph API v2.5

### ISSUE THREAD

**Issue by varmint09** [sahat/satellizer#615]
Hi,

I had to create a new FB App but kept all the code the same except for updating the keys and secret.

I notice now the call made to v2.5 only returns the "name" and the "Id" if the user, not there email and everything else like it did before.

@sahat I just wonder if that is your experience of you create a new App and update all the v2.3's to 2.5 too - or anyone else for that matter. Or is the issue my new apps configure somehow (I just want the standard profile).

I read their Api and the fields are core, just wasn't sure if it breaks satellizer.

I can't lower the Api version to 2.3 either sadly.

**Comment by sahat** [comment]
Yeah I can confirm new apps with API 2.5 do not return email address anymore. But works fine on my existing v2.3 Facebook app.

<img width="571" alt="screenshot 2015-10-25 15 10 46" src="https://cloud.githubusercontent.com/assets/544954/10717327/b7ea620a-7b2a-11e5-8d53-524ce9608dd8.png">
<img width="692" alt="screenshot 2015-10-25 15 09 08" src="https://cloud.githubusercontent.com/assets/544954/10717328/b7f36b0c-7b2a-11e5-830d-e762e1012eae.png">

**Comment by sahat** [comment]
So it seems you have to explicitly pass the `fields` with permissions that you want to get, otherwise it only returns Name and ID. <img width="383" alt="screenshot 2015-10-25 15 24 21" src="https://cloud.githubusercontent.com/assets/544954/10717377/80688490-7b2c-11e5-8e86-515fd9ec2b0f.png">

**Comment by sahat** [comment]
So a temporary solution, you will need to update your back-end URL that makes a Graph API request:

```js
// Node.js
var graphApiUrl = 'https://graph.facebook.com/v2.3/me?fields=name,email';
```

Add additional fields if necessary. 

I will look into how to streamline this process instead of hardcoding permissions in the URL.

**Comment by sahat** [comment]
I ended up using the following approach:

```js
var fields = ['id', 'email', 'first_name', 'last_name', 'link', 'name'];
var graphApiUrl = 'https://graph.facebook.com/v2.5/me?fields=' + fields.join(',');
```

I didn't want to add those fields to Satellizer.js because everyone has different requirements. The nice thing is even if you, for example, do not ask for email permission when signing in with Facebook, this Graph API won't throw an error, it will simply return all other fields except an email.

99f562d540df3137dd83794283b27d6213ba8658

**Comment by dejan7** [comment]
Hello, i noticed one weird thing with the latest version of Satellized and FB api v2.5

Once i click on "login with fb" i get the standard FB popup asking me to login. But once i login i do NOT get the permissions screen (this one:). 

![fb](https://cloud.githubusercontent.com/assets/544954/10717328/b7f36b0c-7b2a-11e5-830d-e762e1012eae.png)

The popup closes and it returns a valid token to my server. However, the issue is that i didn't get the permissions screen, and i wasn't able to give permissions to the app. Therefore i can't get stuff like user email or other things, i can only get user ID and user name, because the token doesn't have proper scopes set.

If i login to my FB account, i don't see the app anywhere under my activity logs, it's like i never logged in. I tried using several different FB app IDs(canvas app, web app, etc), it was always the same. 

This is the URL of the login popup that i get
https://www.facebook.com/login.php?skip_api_login=1&api_key=409617592570102&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.5%2Fdialog%2Foauth%3Fredirect_uri%3Dhttp%253A%252F%252Fpostblazer.dev%252F%26display%3Dpopup%26scope%3Demail%252Cpublic_profile%26response_type%3Dcode%26client_id%3D409617592570102%26ret%3Dlogin&cancel_url=http%3A%2F%2Fpostblazer.dev%2F%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%23_%3D_&display=popup


Any ideas? Thank you!

**Comment by sahat** [comment]
@dejan7 Assuming you are using a valid client id, client secret, redirect uri from your Facebook app, and you say you don't have this app under your Facebook account settings, then I don't see any reason why you don't see the permissions screen. I have never experienced such an issue. On many occassions, I would remove my "Satellizer Local" app from Facebook Apps, and the permissions dialog always shows up.

**Comment by dejan7** [comment]
@sahat Yeah it's really weird, i have no clue why is this happening. I triple checked all the keys and my code. I'm looking through satellizer source too, if i manage to find the problem in satellizer's code i'll create a pull request.
