### ISSUE TITLE
Auth with Facebook has problem

### ISSUE THREAD

**Issue by fordg** [sahat/satellizer#632]
I'm building app using AngularJS and try to make auth with facebook but I've a problem. How to resolve this ?
![screenshot_2](https://cloud.githubusercontent.com/assets/1063803/10961444/7c78cde8-83c1-11e5-9029-a6bf69006839.jpg)

**Comment by sahat** [comment]
Have you googled it?
https://www.facebook.com/help/community/question/?id=542958419109491

**Comment by fordg** [comment]
Yes I've ben googled it, but It's not wok for me

**Comment by sahat** [comment]
Do you have `/auth/facebook` route in your server app?

**Comment by fordg** [comment]
No, I don' t have /auth/facebook, so what can I do for fix it ? Thanks before ..

**Comment by sahat** [comment]
You need to have a server running as well. See one of these examples: https://github.com/sahat/satellizer/tree/master/examples/server

Satellizer uses relies on both client-side and server-side to authorize/authenticate users. If you are running your Sails.js app on a different port, you will need to specify your facebook url explicitly, e.g. 
$authProvider.facebook({
  clientId: '......',
  url: 'http://localhost:8000/auth/facebook'
});
And then you must include a POST route `/auth/facebook` in your Sails.js app. See Node.js example in the examples directory. You should be able to just copy and paste it, maybe with a few slight modifications to suit your needs and make it work with Sails.js.

I am going to close this issue because it's getting hard for me to manage actual bug reports versus questions on how to use Satellizer.
