### ISSUE TITLE
Compatibility with Rails server

### ISSUE THREAD

**Issue by Sergezdv** [sahat/satellizer#691]
Hi @sahat,

I wanted to consult about the plugin https://github.com/sahat/satellizer
Can it be used for combination of AngularJS and Ruby on Rails (server side)

Now for auth we are using ActiveAdmin (with Devise)
I did not find suitable examples and tried to connect Satellizer with Devise and OmniAuth (https://github.com/intridea/omniauth) with the help of gems I chose for the server side
But I did not get the desired result.

Then I saw a similar topic on your repo https://github.com/sahat/satellizer/issues/253
Has anything changed since then? Can you let me know please. 
Will it help if I stop using OmniAuth? Or maybe Devise? Or even if I get rid of all of them I'll still need to invent a bicycle?

Thanks in advance for your response.

**Comment by smnalex** [comment]
Have you solved your problem, or you still need help?

**Comment by sahat** [comment]
@Sergezdv Nothing has changed since then. I am still all for manual approach because it makes my life a lot easier replicating code changes across Node, PHP, Java, Ruby, Python as opposed to learning individual auth libraries for each language. 

But probably more importantly it removes all authentication magic, so anyone can see exactly how each provider is implemented, modify anyway they see fit and add easily a new provider based on existing implementation.

It should be possible to integrate Satellizer with omnioauth and devise. Someone has managed to do it with Passport (node.js) so I assume it shouldn't be too far off. It's just a matter of how much time you want to spend figuring it out. [This step by step flow](https://github.com/sahat/satellizer#-login-with-oauth-20) should help since it tells you where satellizer's responsibility ends and server's responsibility begins.

**Comment by Sergezdv** [comment]
@sahat thanks for your answer. 
I have tried to solve this somehow but probably spent not enough time. It's a pity there is no sample of how someone solved this already. 
I eventually started using a different service - angular_devise which appears to be more suitable for my case. 
Thank you anyway!

**Comment by sahat** [comment]
:+1: @Sergezdv
