### ISSUE TITLE
Native Facebook login

### ISSUE THREAD

**Issue by marcoriesco** [sahat/satellizer#717]
I am implementing a ionic app, I need the Facebook login is native, managed to implement using some examples given by the git Satellizer such as ionic server and the client.

My problem is authentication via Satellizer token.

I am using the https://github.com/Wizcorp/phonegap-facebook-plugin to authenticate via Facebook and other Satellizer for authentication to login and signup without Facebook.

The best method I would modify the satellizer.js own or continue with my implementation by ionic?

**Comment by sahat** [comment]
If you need native look and feel, then you should use that Cordova plugin imho. 

For email and password authentication you don't even need Satellizer because it is so simple. All you need are two input fields and a submit button. You could, however, re-use server implementation: https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js#L155-L196.
