### ISSUE TITLE
Request: Example using OAuth1.0 with Yahoo

### ISSUE THREAD

**Issue by lsbyerley** [sahat/satellizer#779]
First off, just wanted to say thanks for all the great work you've done with Satellizer. Its awesome!

I'm currently working on a MEAN app to utilize the Yahoo Fantasy Sports api (which is still on Oauth1.0) and I can't figure out how to request a token, use this token to request auth, and then receive and access token to hit the Fantasy Sports api. I've tried to follow your steps in the README, but without any luck. 

Would you, or someone, be able to post an example of how to do this? Thanks so much!

**Comment by sahat** [comment]
@lsbyerley You should ask this question on Stack Overflow or Gitter chat room. Otherwise it becomes really hard to keep track of actual issues with the library.

Personally, I have never dealt with Yahoo's OAuth 1.0 flow, hence the example is using OAuth 2.0 authorization protocol. 

You have all the tools you need: ability to create custom OAuth 1.0 and OAuth 2.0 providers with Satellizer, straightforward server-side examples without any library magic demonstrating both OAuth 1.0 and OAuth 2.0 flow. So all you really need to is to research how other people deal with Yahoo Fantasy Sports API. That, however, is outside the scope of this project.
