### ISSUE TITLE
fully client side authentication

### ISSUE THREAD

**Issue by theraaz** [sahat/satellizer#780]
I'm trying to implement twitter login however I saw that it first sends a request to get token from server and then authenticates based on that. Is it possible to do it fully on client side without that extra step?
And yes I know it is discouraged however if hardcoding token on client side is not secure, then it is also not secure to get those using a post request from server I guess.

**Comment by sahat** [comment]
OAuth 1 unfortunately requires that extra step to obtain request token. And request token needs to be obtained on the server because yo should never store Consumer Secret / Client Secret on  the client. When I was writing this library 2 years ago I almost didn't include Twitter due to this limitation, but in the end I chose the workaround you see now. 

Your second point is not correct, since consumer secret key is never sent to the client, only request token, which is necessary to initiate the authorization process.
