### ISSUE TITLE
npm ERR! Refusing to install satellizer as a dependency of itself

### ISSUE THREAD

**Issue by sourh** [sahat/satellizer#812]
I am training to run this project, I am following the steps and when I traied to run this command "  npm install satellizer " I got this error npm ERR! Refusing to install satellizer as a dependency of itself and the template interfaces: home, login ... are not loaded, any help please ?

**Comment by clarle** [comment]
Hi @sourh,

I believe you're trying to install `satellizer` from within the `satellizer` repository, which is why you're getting this issue.

You should be creating your own Angular application, and then installing it from there instead.  

Let me know if that makes sense, or if I can help out more in any way.

Thanks!
