### ISSUE TITLE
$authProvider.facebook url doesnt work

### ISSUE THREAD

**Issue by suharsha** [sahat/satellizer#835]
This doesn't access the route as I'd expect. Every other parameter is working. But this isn't accesing the URL as expected. It works on a default URL but not the one I've specified here.
```js
$authProvider.facebook({
			  name: 'facebook',
			  clientId: '486378764892124',
			  url: '/test/public/api/auth/facebook',
			  authorizationEndpoint: 'https://www.facebook.com/v2.5/dialog/oauth',
			  redirectUri: window.location.origin + '/bargainit/public',
			  requiredUrlParams: ['display', 'scope'],
			  scope: ['email'],
			  scopeDelimiter: ',',
			  display: 'popup',
			  type: '2.0',
			  popupOptions: { width: 580, height: 400 }
			});
```

**Comment by sahat** [comment]
@suharsha When you say URL, do you mean `url` (server-side auth implementation)  or `redirectUri` (where Facebook redirects to) above?

Make sure you can access those endpoints outside of Satellizer first via cURL or Rest API console.

I am going to close this issue because it doesn't look like an issue with Satellizer itself, but rather with your application. If I am incorrect, please feel free to re-open this issue!

Best,
Sahat

**Comment by suharsha** [comment]
@sahat thanks alot. It was indeed an issue with my implementation. I hadn't defined the required permissions in "scope". Now it all works.
