### ISSUE TITLE
FB login fails after google login

### ISSUE THREAD

**Issue by chozabu** [sahat/satellizer#889]
So, after logging in with google, logging out, then trying to log in with facebook - I get this:

http://chozabu.net/autopush/2016-07-22-20-12-781469365.png

"invalid scope: openid" in the fb login window - looking closer, that param is indeed in the URI bar

I noticed in google there is the default ` scopePrefix: 'openid',`
and have worked around this issue by adding `scopePrefix: '',` to facebooks config (along with explicitly setting the scope)

**Comment by justinzelinsky** [comment]
You know, I ran into this issue too but I thought it might have been caused by a bunch changes I was making. I'll look into this.

**Comment by sahat** [comment]
@chozabu Which version of Satellizer are you using? I'll investigate this issue further on my end.

**Comment by sahat** [comment]
@mattlewis92 or @justinzelinsky what would be the easiest way to `new` OAuth1 and OAuth2 services inside `OAuth.ts`?

I believe the issue lies in this code where it is invoking `.init()` on a class rather than an instance of it.   See old Satellizer for reference: https://github.com/sahat/satellizer/blob/old/satellizer.js#L414

I was thinking of creating a new private variables `oauth1` and `oauth2` (lowercase), then inside `OAuth` constructor have something like:

```js
this.oauth2 = new OAuth2($http, $window, $timeout, $q, SatellizerConfig, SatellizerPopup, SatellizerStorage);
this.oauth1 = new OAuth1(.....);
```

This could work but I would need to $inject these services into `OAuth` first, and because they are already injected inside `OAuth1` and `OAuth2` services it seems like a lot of code duplication.

**Comment by mattlewis92** [comment]
Would moving the `this.defaults=` from the constructor to the init method work? You'd also need to do the same on the [popup service](https://github.com/sahat/satellizer/blob/master/src/popup.ts#L20) as well as that looks like it maintains state there as well.

**Comment by sahat** [comment]
@mattlewis92 I think it could work but it would require updating a lot of other parts. Pretty much every OAuth1 and OAuth2 method uses `this.defaults` object.

I am going to go with the approach above until I find a better solution to handle this.

Thanks!

**Comment by sahat** [comment]
Fixed. 2c5e75007a5da91e86549fcf48b87fd423820811

**Comment by chozabu** [comment]
:+1: Fantastic! looks like a good commit - thanks for that :)
