### ISSUE TITLE
NodeJS Examples don't implement Authentication Flow correctly

### ISSUE THREAD

**Issue by xmakina** [sahat/satellizer#962]
At least the Facebook and Google (and presumably all of them) examples (https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js) all fail step 9 of the OAuth2.0 flow. If the user is found, they return an error, rather than a JWT.

This made getting to grips with satellizer more complicated than it needed to be and the examples should be updated accordingly.

**Comment by sahat** [comment]
@xmakina The code which you have modified is related to account linking. If you are simply returning the user, then you are signing in with that other account, rather than linking them. 

Consider the following case: A user has created two accounts by signing in with Facebook, logging out, and then signing in with Google. From the second account, they click on "Link Facebook Account", using your implementation, it will sign user in with their Facebook account. No accounts have been linked.

In a perfect real world scenario what should happen is both accounts to be merged. Since that is very application specific, is it not implemented in the example code. So the next best thing is to throw an error saying that there is already an existing account, i.e. go sign in with that account, or delete it and try to link again.

**Comment by xmakina** [comment]
Ah, okay, that makes sense. I hadn't considered that as it's not in the example flows on the readme. The errors also end up blocking logging in shown in the client example because there's no way to differentiate "login with Facebook"/"login with google" and "link google and facebook accounts together" in the examples given.

So, the quick answer seems to be, what javascript should the user call to ensure that req.header('Authorization') is false?
